
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'LKDataBase_Example' do
  pod 'LKDataBase', :path => '../'

  target 'LKDataBase_Tests' do
    inherit! :search_paths

    
  end
end
